/* SQL text to update entity field related entity name field map for entity field ID 53310620-6A60-4DE3-BA12-DBDAB14B604A */
EXEC [${flyway:defaultSchema}].spUpdateEntityFieldRelatedEntityNameFieldMap
         @EntityFieldID='53310620-6A60-4DE3-BA12-DBDAB14B604A',
         @RelatedEntityNameFieldMap='Meeting'

/* SQL text to update entity field related entity name field map for entity field ID C62E9B04-1EC1-44D6-845B-BF22BC0388A8 */
EXEC [${flyway:defaultSchema}].spUpdateEntityFieldRelatedEntityNameFieldMap
         @EntityFieldID='C62E9B04-1EC1-44D6-845B-BF22BC0388A8',
         @RelatedEntityNameFieldMap='Meeting'

/* Index for Foreign Keys for Artifact */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: Artifacts
-- Item: Index for Foreign Keys
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------
-- Index for foreign key CommitteeID in table Artifact
IF NOT EXISTS (
    SELECT 1
    FROM sys.indexes
    WHERE name = 'IDX_AUTO_MJ_FKEY_Artifact_CommitteeID' 
    AND object_id = OBJECT_ID('[Committees].[Artifact]')
)
CREATE INDEX IDX_AUTO_MJ_FKEY_Artifact_CommitteeID ON [Committees].[Artifact] ([CommitteeID]);

-- Index for foreign key MeetingID in table Artifact
IF NOT EXISTS (
    SELECT 1
    FROM sys.indexes
    WHERE name = 'IDX_AUTO_MJ_FKEY_Artifact_MeetingID' 
    AND object_id = OBJECT_ID('[Committees].[Artifact]')
)
CREATE INDEX IDX_AUTO_MJ_FKEY_Artifact_MeetingID ON [Committees].[Artifact] ([MeetingID]);

-- Index for foreign key AgendaItemID in table Artifact
IF NOT EXISTS (
    SELECT 1
    FROM sys.indexes
    WHERE name = 'IDX_AUTO_MJ_FKEY_Artifact_AgendaItemID' 
    AND object_id = OBJECT_ID('[Committees].[Artifact]')
)
CREATE INDEX IDX_AUTO_MJ_FKEY_Artifact_AgendaItemID ON [Committees].[Artifact] ([AgendaItemID]);

-- Index for foreign key ActionItemID in table Artifact
IF NOT EXISTS (
    SELECT 1
    FROM sys.indexes
    WHERE name = 'IDX_AUTO_MJ_FKEY_Artifact_ActionItemID' 
    AND object_id = OBJECT_ID('[Committees].[Artifact]')
)
CREATE INDEX IDX_AUTO_MJ_FKEY_Artifact_ActionItemID ON [Committees].[Artifact] ([ActionItemID]);

-- Index for foreign key UploadedByUserID in table Artifact
IF NOT EXISTS (
    SELECT 1
    FROM sys.indexes
    WHERE name = 'IDX_AUTO_MJ_FKEY_Artifact_UploadedByUserID' 
    AND object_id = OBJECT_ID('[Committees].[Artifact]')
)
CREATE INDEX IDX_AUTO_MJ_FKEY_Artifact_UploadedByUserID ON [Committees].[Artifact] ([UploadedByUserID]);

/* SQL text to update entity field related entity name field map for entity field ID F9884E7C-7C2A-4FFF-BCB8-880B276DCDCC */
EXEC [${flyway:defaultSchema}].spUpdateEntityFieldRelatedEntityNameFieldMap
         @EntityFieldID='F9884E7C-7C2A-4FFF-BCB8-880B276DCDCC',
         @RelatedEntityNameFieldMap='Meeting'

/* SQL text to update entity field related entity name field map for entity field ID ED3579CB-4AA3-44F1-8EA7-901277CFC870 */
EXEC [${flyway:defaultSchema}].spUpdateEntityFieldRelatedEntityNameFieldMap
         @EntityFieldID='ED3579CB-4AA3-44F1-8EA7-901277CFC870',
         @RelatedEntityNameFieldMap='Meeting'

/* SQL text to update entity field related entity name field map for entity field ID D591C8FF-CAA1-4BA0-A13E-31E900A49286 */
EXEC [${flyway:defaultSchema}].spUpdateEntityFieldRelatedEntityNameFieldMap
         @EntityFieldID='D591C8FF-CAA1-4BA0-A13E-31E900A49286',
         @RelatedEntityNameFieldMap='ActionItem'

/* Base View SQL for Artifacts */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: Artifacts
-- Item: vwArtifacts
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------

------------------------------------------------------------
----- BASE VIEW FOR ENTITY:      Artifacts
-----               SCHEMA:      Committees
-----               BASE TABLE:  Artifact
-----               PRIMARY KEY: ID
------------------------------------------------------------
IF OBJECT_ID('[Committees].[vwArtifacts]', 'V') IS NOT NULL
    DROP VIEW [Committees].[vwArtifacts];
GO

CREATE VIEW [Committees].[vwArtifacts]
AS
SELECT
    a.*,
    Committee_CommitteeID.[Name] AS [Committee],
    Meeting_MeetingID.[Title] AS [Meeting],
    ActionItem_ActionItemID.[Title] AS [ActionItem],
    User_UploadedByUserID.[Name] AS [UploadedByUser]
FROM
    [Committees].[Artifact] AS a
LEFT OUTER JOIN
    [Committees].[Committee] AS Committee_CommitteeID
  ON
    [a].[CommitteeID] = Committee_CommitteeID.[ID]
LEFT OUTER JOIN
    [Committees].[Meeting] AS Meeting_MeetingID
  ON
    [a].[MeetingID] = Meeting_MeetingID.[ID]
LEFT OUTER JOIN
    [Committees].[ActionItem] AS ActionItem_ActionItemID
  ON
    [a].[ActionItemID] = ActionItem_ActionItemID.[ID]
LEFT OUTER JOIN
    [${flyway:defaultSchema}].[User] AS User_UploadedByUserID
  ON
    [a].[UploadedByUserID] = User_UploadedByUserID.[ID]
GO
GRANT SELECT ON [Committees].[vwArtifacts] TO [cdp_UI], [cdp_Developer], [cdp_Integration]
    

/* Base View Permissions SQL for Artifacts */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: Artifacts
-- Item: Permissions for vwArtifacts
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------

GRANT SELECT ON [Committees].[vwArtifacts] TO [cdp_UI], [cdp_Developer], [cdp_Integration]

/* spCreate SQL for Artifacts */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: Artifacts
-- Item: spCreateArtifact
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------

------------------------------------------------------------
----- CREATE PROCEDURE FOR Artifact
------------------------------------------------------------
IF OBJECT_ID('[Committees].[spCreateArtifact]', 'P') IS NOT NULL
    DROP PROCEDURE [Committees].[spCreateArtifact];
GO

CREATE PROCEDURE [Committees].[spCreateArtifact]
    @ID uniqueidentifier = NULL,
    @CommitteeID uniqueidentifier,
    @MeetingID uniqueidentifier,
    @AgendaItemID uniqueidentifier,
    @ActionItemID uniqueidentifier,
    @Title nvarchar(255),
    @Description nvarchar(MAX),
    @Provider nvarchar(50),
    @ExternalID nvarchar(500),
    @URL nvarchar(2000),
    @MimeType nvarchar(100),
    @FileSize bigint,
    @UploadedByUserID uniqueidentifier,
    @ArtifactType nvarchar(50) = NULL
AS
BEGIN
    SET NOCOUNT ON;
    DECLARE @InsertedRow TABLE ([ID] UNIQUEIDENTIFIER)
    
    IF @ID IS NOT NULL
    BEGIN
        -- User provided a value, use it
        INSERT INTO [Committees].[Artifact]
            (
                [ID],
                [CommitteeID],
                [MeetingID],
                [AgendaItemID],
                [ActionItemID],
                [Title],
                [Description],
                [Provider],
                [ExternalID],
                [URL],
                [MimeType],
                [FileSize],
                [UploadedByUserID],
                [ArtifactType]
            )
        OUTPUT INSERTED.[ID] INTO @InsertedRow
        VALUES
            (
                @ID,
                @CommitteeID,
                @MeetingID,
                @AgendaItemID,
                @ActionItemID,
                @Title,
                @Description,
                @Provider,
                @ExternalID,
                @URL,
                @MimeType,
                @FileSize,
                @UploadedByUserID,
                ISNULL(@ArtifactType, 'Document')
            )
    END
    ELSE
    BEGIN
        -- No value provided, let database use its default (e.g., NEWSEQUENTIALID())
        INSERT INTO [Committees].[Artifact]
            (
                [CommitteeID],
                [MeetingID],
                [AgendaItemID],
                [ActionItemID],
                [Title],
                [Description],
                [Provider],
                [ExternalID],
                [URL],
                [MimeType],
                [FileSize],
                [UploadedByUserID],
                [ArtifactType]
            )
        OUTPUT INSERTED.[ID] INTO @InsertedRow
        VALUES
            (
                @CommitteeID,
                @MeetingID,
                @AgendaItemID,
                @ActionItemID,
                @Title,
                @Description,
                @Provider,
                @ExternalID,
                @URL,
                @MimeType,
                @FileSize,
                @UploadedByUserID,
                ISNULL(@ArtifactType, 'Document')
            )
    END
    -- return the new record from the base view, which might have some calculated fields
    SELECT * FROM [Committees].[vwArtifacts] WHERE [ID] = (SELECT [ID] FROM @InsertedRow)
END
GO
GRANT EXECUTE ON [Committees].[spCreateArtifact] TO [cdp_Developer], [cdp_Integration]
    

/* spCreate Permissions for Artifacts */

GRANT EXECUTE ON [Committees].[spCreateArtifact] TO [cdp_Developer], [cdp_Integration]



/* spUpdate SQL for Artifacts */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: Artifacts
-- Item: spUpdateArtifact
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------

------------------------------------------------------------
----- UPDATE PROCEDURE FOR Artifact
------------------------------------------------------------
IF OBJECT_ID('[Committees].[spUpdateArtifact]', 'P') IS NOT NULL
    DROP PROCEDURE [Committees].[spUpdateArtifact];
GO

CREATE PROCEDURE [Committees].[spUpdateArtifact]
    @ID uniqueidentifier,
    @CommitteeID uniqueidentifier,
    @MeetingID uniqueidentifier,
    @AgendaItemID uniqueidentifier,
    @ActionItemID uniqueidentifier,
    @Title nvarchar(255),
    @Description nvarchar(MAX),
    @Provider nvarchar(50),
    @ExternalID nvarchar(500),
    @URL nvarchar(2000),
    @MimeType nvarchar(100),
    @FileSize bigint,
    @UploadedByUserID uniqueidentifier,
    @ArtifactType nvarchar(50)
AS
BEGIN
    SET NOCOUNT ON;
    UPDATE
        [Committees].[Artifact]
    SET
        [CommitteeID] = @CommitteeID,
        [MeetingID] = @MeetingID,
        [AgendaItemID] = @AgendaItemID,
        [ActionItemID] = @ActionItemID,
        [Title] = @Title,
        [Description] = @Description,
        [Provider] = @Provider,
        [ExternalID] = @ExternalID,
        [URL] = @URL,
        [MimeType] = @MimeType,
        [FileSize] = @FileSize,
        [UploadedByUserID] = @UploadedByUserID,
        [ArtifactType] = @ArtifactType
    WHERE
        [ID] = @ID

    -- Check if the update was successful
    IF @@ROWCOUNT = 0
        -- Nothing was updated, return no rows, but column structure from base view intact, semantically correct this way.
        SELECT TOP 0 * FROM [Committees].[vwArtifacts] WHERE 1=0
    ELSE
        -- Return the updated record so the caller can see the updated values and any calculated fields
        SELECT
                                        *
                                    FROM
                                        [Committees].[vwArtifacts]
                                    WHERE
                                        [ID] = @ID
                                    
END
GO

GRANT EXECUTE ON [Committees].[spUpdateArtifact] TO [cdp_Developer], [cdp_Integration]
GO

------------------------------------------------------------
----- TRIGGER FOR __mj_UpdatedAt field for the Artifact table
------------------------------------------------------------
IF OBJECT_ID('[Committees].[trgUpdateArtifact]', 'TR') IS NOT NULL
    DROP TRIGGER [Committees].[trgUpdateArtifact];
GO
CREATE TRIGGER [Committees].trgUpdateArtifact
ON [Committees].[Artifact]
AFTER UPDATE
AS
BEGIN
    SET NOCOUNT ON;
    UPDATE
        [Committees].[Artifact]
    SET
        __mj_UpdatedAt = GETUTCDATE()
    FROM
        [Committees].[Artifact] AS _organicTable
    INNER JOIN
        INSERTED AS I ON
        _organicTable.[ID] = I.[ID];
END;
GO
        

/* spUpdate Permissions for Artifacts */

GRANT EXECUTE ON [Committees].[spUpdateArtifact] TO [cdp_Developer], [cdp_Integration]



/* spDelete SQL for Artifacts */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: Artifacts
-- Item: spDeleteArtifact
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------

------------------------------------------------------------
----- DELETE PROCEDURE FOR Artifact
------------------------------------------------------------
IF OBJECT_ID('[Committees].[spDeleteArtifact]', 'P') IS NOT NULL
    DROP PROCEDURE [Committees].[spDeleteArtifact];
GO

CREATE PROCEDURE [Committees].[spDeleteArtifact]
    @ID uniqueidentifier
AS
BEGIN
    SET NOCOUNT ON;

    DELETE FROM
        [Committees].[Artifact]
    WHERE
        [ID] = @ID


    -- Check if the delete was successful
    IF @@ROWCOUNT = 0
        SELECT NULL AS [ID] -- Return NULL for all primary key fields to indicate no record was deleted
    ELSE
        SELECT @ID AS [ID] -- Return the primary key values to indicate we successfully deleted the record
END
GO
GRANT EXECUTE ON [Committees].[spDeleteArtifact] TO [cdp_Integration]
    

/* spDelete Permissions for Artifacts */

GRANT EXECUTE ON [Committees].[spDeleteArtifact] TO [cdp_Integration]



/* SQL text to insert new entity field */

      IF NOT EXISTS (
         SELECT 1 FROM [${flyway:defaultSchema}].EntityField 
         WHERE ID = 'a4c1f92c-7604-4125-a4b1-6a9b10e41d79'  OR 
               (EntityID = 'F8AA4C3C-5F9B-46DA-945E-C6DD36D83C22' AND Name = 'Meeting')
         -- check to make sure we're not inserting a duplicate entity field metadata record
      )
      BEGIN
         INSERT INTO [${flyway:defaultSchema}].EntityField
         (
            ID,
            EntityID,
            Sequence,
            Name,
            DisplayName,
            Description,
            Type,
            Length,
            Precision,
            Scale,
            AllowsNull,
            DefaultValue,
            AutoIncrement,
            AllowUpdateAPI,
            IsVirtual,
            RelatedEntityID,
            RelatedEntityFieldName,
            IsNameField,
            IncludeInUserSearchAPI,
            IncludeRelatedEntityNameFieldInBaseView,
            DefaultInView,
            IsPrimaryKey,
            IsUnique,
            RelatedEntityDisplayType
         )
         VALUES
         (
            'a4c1f92c-7604-4125-a4b1-6a9b10e41d79',
            'F8AA4C3C-5F9B-46DA-945E-C6DD36D83C22', -- Entity: Artifacts
            100036,
            'Meeting',
            'Meeting',
            NULL,
            'nvarchar',
            510,
            0,
            0,
            1,
            'null',
            0,
            0,
            1,
            NULL,
            NULL,
            0,
            0,
            0,
            0,
            0,
            0,
            'Search'
         )
      END

/* SQL text to insert new entity field */

      IF NOT EXISTS (
         SELECT 1 FROM [${flyway:defaultSchema}].EntityField 
         WHERE ID = 'b5656ecd-8994-4736-8b6e-3e7668ead942'  OR 
               (EntityID = 'F8AA4C3C-5F9B-46DA-945E-C6DD36D83C22' AND Name = 'ActionItem')
         -- check to make sure we're not inserting a duplicate entity field metadata record
      )
      BEGIN
         INSERT INTO [${flyway:defaultSchema}].EntityField
         (
            ID,
            EntityID,
            Sequence,
            Name,
            DisplayName,
            Description,
            Type,
            Length,
            Precision,
            Scale,
            AllowsNull,
            DefaultValue,
            AutoIncrement,
            AllowUpdateAPI,
            IsVirtual,
            RelatedEntityID,
            RelatedEntityFieldName,
            IsNameField,
            IncludeInUserSearchAPI,
            IncludeRelatedEntityNameFieldInBaseView,
            DefaultInView,
            IsPrimaryKey,
            IsUnique,
            RelatedEntityDisplayType
         )
         VALUES
         (
            'b5656ecd-8994-4736-8b6e-3e7668ead942',
            'F8AA4C3C-5F9B-46DA-945E-C6DD36D83C22', -- Entity: Artifacts
            100037,
            'ActionItem',
            'Action Item',
            NULL,
            'nvarchar',
            510,
            0,
            0,
            1,
            'null',
            0,
            0,
            1,
            NULL,
            NULL,
            0,
            0,
            0,
            0,
            0,
            0,
            'Search'
         )
      END

/* Set field properties for entity */

            UPDATE [${flyway:defaultSchema}].EntityField
            SET IsNameField = 1
            WHERE ID = '02CD9070-98E0-4C38-BDC9-A50C59283FE9'
            AND AutoUpdateIsNameField = 1
         

            UPDATE [${flyway:defaultSchema}].EntityField
            SET DefaultInView = 1
            WHERE ID = '02CD9070-98E0-4C38-BDC9-A50C59283FE9'
            AND AutoUpdateDefaultInView = 1
         

            UPDATE [${flyway:defaultSchema}].EntityField
            SET DefaultInView = 1
            WHERE ID = 'F74F8435-D009-47A0-8C20-F48C806E00C7'
            AND AutoUpdateDefaultInView = 1
         

            UPDATE [${flyway:defaultSchema}].EntityField
            SET DefaultInView = 1
            WHERE ID = 'EA5DE8BE-9A7A-47FE-A605-3E8B2B34C6D0'
            AND AutoUpdateDefaultInView = 1
         

            UPDATE [${flyway:defaultSchema}].EntityField
            SET DefaultInView = 1
            WHERE ID = '492ADC5A-6CE8-4FA1-907C-92A053063F7B'
            AND AutoUpdateDefaultInView = 1
         

               UPDATE [${flyway:defaultSchema}].EntityField
               SET IncludeInUserSearchAPI = 1
               WHERE ID = '02CD9070-98E0-4C38-BDC9-A50C59283FE9'
               AND AutoUpdateIncludeInUserSearchAPI = 1
            

               UPDATE [${flyway:defaultSchema}].EntityField
               SET IncludeInUserSearchAPI = 1
               WHERE ID = 'F74F8435-D009-47A0-8C20-F48C806E00C7'
               AND AutoUpdateIncludeInUserSearchAPI = 1
            

               UPDATE [${flyway:defaultSchema}].EntityField
               SET IncludeInUserSearchAPI = 1
               WHERE ID = '81DAA0C0-8357-45ED-9614-20AA86C8B06C'
               AND AutoUpdateIncludeInUserSearchAPI = 1
            

               UPDATE [${flyway:defaultSchema}].EntityField
               SET IncludeInUserSearchAPI = 1
               WHERE ID = '4CD775D6-1A20-4DF1-A8CC-9AE1A1044A13'
               AND AutoUpdateIncludeInUserSearchAPI = 1
            

               UPDATE [${flyway:defaultSchema}].EntityField
               SET IncludeInUserSearchAPI = 1
               WHERE ID = 'EA5DE8BE-9A7A-47FE-A605-3E8B2B34C6D0'
               AND AutoUpdateIncludeInUserSearchAPI = 1
            

               UPDATE [${flyway:defaultSchema}].EntityField
               SET IncludeInUserSearchAPI = 1
               WHERE ID = '35C3D4E8-DEA8-4186-B70D-B7FD96549F5D'
               AND AutoUpdateIncludeInUserSearchAPI = 1
            

               UPDATE [${flyway:defaultSchema}].EntityField
               SET IncludeInUserSearchAPI = 1
               WHERE ID = 'A4C1F92C-7604-4125-A4B1-6A9B10E41D79'
               AND AutoUpdateIncludeInUserSearchAPI = 1
            

               UPDATE [${flyway:defaultSchema}].EntityField
               SET IncludeInUserSearchAPI = 1
               WHERE ID = 'B5656ECD-8994-4736-8B6E-3E7668EAD942'
               AND AutoUpdateIncludeInUserSearchAPI = 1
            

               UPDATE [${flyway:defaultSchema}].EntityField
               SET IncludeInUserSearchAPI = 1
               WHERE ID = '492ADC5A-6CE8-4FA1-907C-92A053063F7B'
               AND AutoUpdateIncludeInUserSearchAPI = 1
            

/* Set categories for 20 fields */
UPDATE [${flyway:defaultSchema}].EntityField
   SET Category = 'System Metadata',
       GeneratedFormSection = 'Category',
       DisplayName = 'ID',
       ExtendedType = NULL,
       CodeType = NULL
   WHERE ID = 'EFC3B519-E2E1-4546-B704-D9AEA36B8D0C'
   AND AutoUpdateCategory = 1
UPDATE [${flyway:defaultSchema}].EntityField
   SET Category = 'System Metadata',
       GeneratedFormSection = 'Category',
       DisplayName = 'Created At',
       ExtendedType = NULL,
       CodeType = NULL
   WHERE ID = '781CC137-E299-4D9B-AA32-DFC03FE79D27'
   AND AutoUpdateCategory = 1
UPDATE [${flyway:defaultSchema}].EntityField
   SET Category = 'System Metadata',
       GeneratedFormSection = 'Category',
       DisplayName = 'Updated At',
       ExtendedType = NULL,
       CodeType = NULL
   WHERE ID = '22F5495A-D51A-49C9-B599-3C7AC29054A0'
   AND AutoUpdateCategory = 1
UPDATE [${flyway:defaultSchema}].EntityField
   SET Category = 'Related Entities',
       GeneratedFormSection = 'Category',
       DisplayName = 'Committee',
       ExtendedType = NULL,
       CodeType = NULL
   WHERE ID = 'EFB5BC31-DB80-4D85-BC13-5C831202245A'
   AND AutoUpdateCategory = 1
UPDATE [${flyway:defaultSchema}].EntityField
   SET Category = 'Related Entities',
       GeneratedFormSection = 'Category',
       DisplayName = 'Meeting',
       ExtendedType = NULL,
       CodeType = NULL
   WHERE ID = 'F9884E7C-7C2A-4FFF-BCB8-880B276DCDCC'
   AND AutoUpdateCategory = 1
UPDATE [${flyway:defaultSchema}].EntityField
   SET Category = 'Related Entities',
       GeneratedFormSection = 'Category',
       DisplayName = 'Agenda Item',
       ExtendedType = NULL,
       CodeType = NULL
   WHERE ID = 'C52E97D9-5AEF-47C7-BEE3-3FDFA483DBCE'
   AND AutoUpdateCategory = 1
UPDATE [${flyway:defaultSchema}].EntityField
   SET Category = 'Related Entities',
       GeneratedFormSection = 'Category',
       DisplayName = 'Action Item',
       ExtendedType = NULL,
       CodeType = NULL
   WHERE ID = 'D591C8FF-CAA1-4BA0-A13E-31E900A49286'
   AND AutoUpdateCategory = 1
UPDATE [${flyway:defaultSchema}].EntityField
   SET Category = 'Related Entities',
       GeneratedFormSection = 'Category',
       DisplayName = 'Uploaded By User',
       ExtendedType = NULL,
       CodeType = NULL
   WHERE ID = 'B7FB77DB-BD43-4FB5-9476-B3C546FFB6F2'
   AND AutoUpdateCategory = 1
UPDATE [${flyway:defaultSchema}].EntityField
   SET Category = 'Related Entities',
       GeneratedFormSection = 'Category',
       DisplayName = 'Committee',
       ExtendedType = NULL,
       CodeType = NULL
   WHERE ID = '35C3D4E8-DEA8-4186-B70D-B7FD96549F5D'
   AND AutoUpdateCategory = 1
UPDATE [${flyway:defaultSchema}].EntityField
   SET Category = 'Related Entities',
       GeneratedFormSection = 'Category',
       DisplayName = 'Meeting',
       ExtendedType = NULL,
       CodeType = NULL
   WHERE ID = 'A4C1F92C-7604-4125-A4B1-6A9B10E41D79'
   AND AutoUpdateCategory = 1
UPDATE [${flyway:defaultSchema}].EntityField
   SET Category = 'Related Entities',
       GeneratedFormSection = 'Category',
       DisplayName = 'Action Item',
       ExtendedType = NULL,
       CodeType = NULL
   WHERE ID = 'B5656ECD-8994-4736-8B6E-3E7668EAD942'
   AND AutoUpdateCategory = 1
UPDATE [${flyway:defaultSchema}].EntityField
   SET Category = 'Related Entities',
       GeneratedFormSection = 'Category',
       DisplayName = 'Uploaded By User',
       ExtendedType = NULL,
       CodeType = NULL
   WHERE ID = '492ADC5A-6CE8-4FA1-907C-92A053063F7B'
   AND AutoUpdateCategory = 1
UPDATE [${flyway:defaultSchema}].EntityField
   SET Category = 'Artifact Details',
       GeneratedFormSection = 'Category',
       DisplayName = 'Title',
       ExtendedType = NULL,
       CodeType = NULL
   WHERE ID = '02CD9070-98E0-4C38-BDC9-A50C59283FE9'
   AND AutoUpdateCategory = 1
UPDATE [${flyway:defaultSchema}].EntityField
   SET Category = 'Artifact Details',
       GeneratedFormSection = 'Category',
       DisplayName = 'Description',
       ExtendedType = NULL,
       CodeType = NULL
   WHERE ID = '15B869C2-B866-4510-B2FA-5B9F6A914CE2'
   AND AutoUpdateCategory = 1
UPDATE [${flyway:defaultSchema}].EntityField
   SET Category = 'Artifact Details',
       GeneratedFormSection = 'Category',
       DisplayName = 'Artifact Type',
       ExtendedType = NULL,
       CodeType = NULL
   WHERE ID = 'EA5DE8BE-9A7A-47FE-A605-3E8B2B34C6D0'
   AND AutoUpdateCategory = 1
UPDATE [${flyway:defaultSchema}].EntityField
   SET Category = 'Storage Information',
       GeneratedFormSection = 'Category',
       DisplayName = 'Provider',
       ExtendedType = NULL,
       CodeType = NULL
   WHERE ID = 'F74F8435-D009-47A0-8C20-F48C806E00C7'
   AND AutoUpdateCategory = 1
UPDATE [${flyway:defaultSchema}].EntityField
   SET Category = 'Storage Information',
       GeneratedFormSection = 'Category',
       DisplayName = 'External ID',
       ExtendedType = NULL,
       CodeType = NULL
   WHERE ID = '81DAA0C0-8357-45ED-9614-20AA86C8B06C'
   AND AutoUpdateCategory = 1
UPDATE [${flyway:defaultSchema}].EntityField
   SET Category = 'Storage Information',
       GeneratedFormSection = 'Category',
       DisplayName = 'URL',
       ExtendedType = 'URL',
       CodeType = NULL
   WHERE ID = '4CD775D6-1A20-4DF1-A8CC-9AE1A1044A13'
   AND AutoUpdateCategory = 1
UPDATE [${flyway:defaultSchema}].EntityField
   SET Category = 'Storage Information',
       GeneratedFormSection = 'Category',
       DisplayName = 'MIME Type',
       ExtendedType = NULL,
       CodeType = NULL
   WHERE ID = 'E84825D5-9E86-475E-A7B6-3FE75EAD6405'
   AND AutoUpdateCategory = 1
UPDATE [${flyway:defaultSchema}].EntityField
   SET Category = 'Storage Information',
       GeneratedFormSection = 'Category',
       DisplayName = 'File Size',
       ExtendedType = NULL,
       CodeType = NULL
   WHERE ID = '90A51F1E-4F5A-412E-ADC0-25A2FEDD9875'
   AND AutoUpdateCategory = 1

/* Update FieldCategoryInfo setting for entity */

               UPDATE [${flyway:defaultSchema}].EntitySetting
               SET Value = '{"Artifact Details":{"icon":"fa fa-file-alt","description":"Core descriptive information about the artifact"},"Storage Information":{"icon":"fa fa-cloud","description":"Provider and technical details for accessing the stored artifact"},"Related Entities":{"icon":"fa fa-link","description":"Links the artifact to committees, meetings, agenda items, actions and uploader"},"System Metadata":{"icon":"fa fa-cog","description":"System-managed audit and identifier fields"}}',
                   __mj_UpdatedAt = GETUTCDATE()
               WHERE EntityID = 'F8AA4C3C-5F9B-46DA-945E-C6DD36D83C22' AND Name = 'FieldCategoryInfo'
            

/* Update FieldCategoryIcons setting for entity (legacy format) */

               UPDATE [${flyway:defaultSchema}].EntitySetting
               SET Value = '{"Artifact Details":"fa fa-file-alt","Storage Information":"fa fa-cloud","Related Entities":"fa fa-link","System Metadata":"fa fa-cog"}',
                   __mj_UpdatedAt = GETUTCDATE()
               WHERE EntityID = 'F8AA4C3C-5F9B-46DA-945E-C6DD36D83C22' AND Name = 'FieldCategoryIcons'
            

